In [14]:
import torch

x1 = torch.tensor([2.0, 3.0], requires_grad=True)
x2 = torch.tensor([1.0, 4.0], requires_grad=True)

print(a, b)

q = 3*x1**3 - 2*x2**2
print(q)

q.backward(gradient=torch.tensor([1., 1.]))
print(x1.grad, x2.grad)

tensor([2., 3.], requires_grad=True) tensor([1., 4.], requires_grad=True)
tensor([22., 49.], grad_fn=<SubBackward0>)
tensor([36., 81.]) tensor([ -4., -16.])
